build:
	@vivado -mode batch -nojournal -nolog -source build.tcl

synth:
	@vivado -mode batch -nojournal -nolog -source synth.tcl

flash:
	@vivado -mode batch -nojournal -nolog -source flash.tcl

select:
	@vivado -mode batch -nojournal -nolog -source flash_select.tcl
